import { useEffect, useState } from "react";
import AppLayout from "../components/AppLayout";
import { equipmentService, laboratoryService } from "../services/entityService";

function Equipments() {
  const emptyForm = { nom: "", modele: "nouveau", description: "", LaboratoryId: "" };
  const [items, setItems] = useState([]); const [labs, setLabs] = useState([]); const [form, setForm] = useState(emptyForm); const [editId, setEditId] = useState(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const load = async () => { try { setLoading(true); const [eqRes, labRes] = await Promise.all([equipmentService.getAll(), laboratoryService.getAll()]); setItems(eqRes?.data?.equipments || []); setLabs(labRes?.data?.laboratories || []); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const submit = async (e) => { e.preventDefault(); if (!form.nom.trim() || !form.LaboratoryId) return setError("Nom et laboratoire obligatoires."); try { setSaving(true); const payload = { ...form, LaboratoryId: Number(form.LaboratoryId) }; if (editId) await equipmentService.update(editId, payload); else await equipmentService.create(payload); setMessage(editId ? "Équipement modifié." : "Équipement ajouté."); setForm(emptyForm); setEditId(null); load(); } catch (e) { setError(e.message); } finally { setSaving(false); } };
  const remove = async (id) => { if (!window.confirm("Supprimer cet équipement ?")) return; try { await equipmentService.remove(id); setMessage("Équipement supprimé."); load(); } catch (e) { setError(e.message); } };
  const edit = (it) => { setForm({ nom: it.nom || "", modele: it.modele || "nouveau", description: it.description || "", LaboratoryId: it.LaboratoryId ? String(it.LaboratoryId) : "" }); setEditId(it.id); };
  return <AppLayout title="Équipements"><section className="form-card"><form className="entity-form" onSubmit={submit}><div className="form-grid"><div><label>Nom</label><input value={form.nom} onChange={(e) => setForm({ ...form, nom: e.target.value })} /></div><div><label>Modèle</label><select value={form.modele} onChange={(e) => setForm({ ...form, modele: e.target.value })}><option value="nouveau">nouveau</option><option value="ancien">ancien</option><option value="refait">refait</option></select></div><div className="full-width"><label>Description</label><textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></div><div><label>Laboratoire</label><select value={form.LaboratoryId} onChange={(e) => setForm({ ...form, LaboratoryId: e.target.value })}><option value="">-- Choisir --</option>{labs.map((l) => <option key={l.id} value={l.id}>{l.nom}</option>)}</select></div></div>{message && <p className="success-text">{message}</p>}{error && <p className="error-text">{error}</p>}<div className="form-actions"><button className="primary-btn" disabled={saving}>{saving ? "Enregistrement..." : editId ? "Modifier" : "Ajouter"}</button>{editId && <button type="button" className="ghost-btn" onClick={() => { setForm(emptyForm); setEditId(null); }}>Annuler</button>}</div></form></section>{loading ? <section className="state-box">Chargement...</section> : <section className="card-grid" style={{ marginTop: 20 }}>{items.map((it) => <article className="entity-card" key={it.id}><div className="card-body"><h3>{it.nom}</h3><p className="entity-badge">{it.modele}</p><p className="card-description">{it.description || "Aucune description"}</p><p className="muted-text">Laboratoire: {it.Laboratory?.nom || "—"}</p></div><div className="card-actions"><button className="ghost-btn" onClick={() => edit(it)}>Modifier</button><button className="danger-btn" onClick={() => remove(it.id)}>Supprimer</button></div></article>)}</section>}</AppLayout>;
}

export default Equipments;
