import { useEffect, useState } from "react";
import AppLayout from "../components/AppLayout";
import { departmentService, laboratoryService } from "../services/entityService";

function Laboratories() {
  const emptyForm = { nom: "", salle: "", information: "", DepartmentId: "" };
  const [items, setItems] = useState([]); const [departments, setDepartments] = useState([]); const [form, setForm] = useState(emptyForm); const [editId, setEditId] = useState(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const load = async () => { try { setLoading(true); const [labs, deps] = await Promise.all([laboratoryService.getAll(), departmentService.getAll()]); setItems(labs?.data?.laboratories || []); setDepartments(deps?.data?.departments || []); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const validate = () => form.nom.trim() && form.DepartmentId;
  const submit = async (e) => { e.preventDefault(); setError(""); setMessage(""); if (!validate()) return setError("Nom et département obligatoires."); try { setSaving(true); const payload = { ...form, DepartmentId: Number(form.DepartmentId) }; if (editId) await laboratoryService.update(editId, payload); else await laboratoryService.create(payload); setMessage(editId ? "Laboratoire modifié." : "Laboratoire ajouté."); setForm(emptyForm); setEditId(null); load(); } catch (e) { setError(e.message); } finally { setSaving(false); } };
  const remove = async (id) => { if (!window.confirm("Supprimer ce laboratoire ?")) return; try { await laboratoryService.remove(id); setMessage("Laboratoire supprimé."); load(); } catch (e) { setError(e.message); } };
  const edit = (item) => { setForm({ nom: item.nom || "", salle: item.salle || "", information: item.information || "", DepartmentId: item.DepartmentId ? String(item.DepartmentId) : "" }); setEditId(item.id); };
  return <AppLayout title="Laboratoires"><section className="form-card"><form className="entity-form" onSubmit={submit}><div className="form-grid"><div><label>Nom</label><input value={form.nom} onChange={(e) => setForm({ ...form, nom: e.target.value })} /></div><div><label>Salle</label><input value={form.salle} onChange={(e) => setForm({ ...form, salle: e.target.value })} /></div><div className="full-width"><label>Information</label><textarea value={form.information} onChange={(e) => setForm({ ...form, information: e.target.value })} /></div><div><label>Département</label><select value={form.DepartmentId} onChange={(e) => setForm({ ...form, DepartmentId: e.target.value })}><option value="">-- Choisir --</option>{departments.map((d) => <option key={d.id} value={d.id}>{d.nom}</option>)}</select></div></div>{message && <p className="success-text">{message}</p>}{error && <p className="error-text">{error}</p>}<div className="form-actions"><button className="primary-btn" disabled={saving}>{saving ? "Enregistrement..." : editId ? "Modifier" : "Ajouter"}</button>{editId && <button type="button" className="ghost-btn" onClick={() => { setForm(emptyForm); setEditId(null); }}>Annuler</button>}</div></form></section>{loading ? <section className="state-box">Chargement...</section> : <section className="card-grid" style={{ marginTop: 20 }}>{items.map((lab) => <article className="entity-card" key={lab.id}><div className="card-body"><h3>{lab.nom}</h3><p className="muted-text"><strong>Salle :</strong> {lab.salle || "—"}</p><p className="card-description">{lab.information || "Aucune information"}</p><p className="muted-text">Département: {lab.Department?.nom || "—"}</p></div><div className="card-actions"><button className="ghost-btn" onClick={() => edit(lab)}>Modifier</button><button className="danger-btn" onClick={() => remove(lab.id)}>Supprimer</button></div></article>)}</section>}</AppLayout>;
}

export default Laboratories;
