import { useEffect, useState } from "react";
import AppLayout from "../components/AppLayout";
import { departmentService, userService } from "../services/entityService";

function Users() {
  const emptyForm = { nom: "", prenom: "", email: "", mot_de_passe: "", naissance: "", conduite: "", DepartmentId: "" };
  const [items, setItems] = useState([]); const [departments, setDepartments] = useState([]); const [form, setForm] = useState(emptyForm); const [editId, setEditId] = useState(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [fieldErrors, setFieldErrors] = useState({});
  const load = async () => { try { setLoading(true); const [usersRes, depsRes] = await Promise.all([userService.getAll(), departmentService.getAll()]); setItems(usersRes?.data?.users || []); setDepartments(depsRes?.data?.departments || []); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const validate = () => { const next = {}; if (!form.nom.trim()) next.nom = "Le nom est obligatoire."; if (!form.prenom.trim()) next.prenom = "Le prénom est obligatoire."; if (!form.email.trim()) next.email = "L'email est obligatoire."; else if (!/^\S+@\S+\.\S+$/.test(form.email)) next.email = "Email invalide."; if (!editId && !form.mot_de_passe.trim()) next.mot_de_passe = "Le mot de passe est obligatoire."; return next; };
  const submit = async (e) => { e.preventDefault(); setError(""); setMessage(""); const next = validate(); setFieldErrors(next); if (Object.keys(next).length) return setError("Veuillez corriger les champs en rouge."); try { setSaving(true); const payload = { ...form, DepartmentId: form.DepartmentId ? Number(form.DepartmentId) : undefined }; if (editId && !payload.mot_de_passe) delete payload.mot_de_passe; if (editId) await userService.update(editId, payload); else await userService.create(payload); setMessage(editId ? "Utilisateur modifié." : "Utilisateur ajouté."); setForm(emptyForm); setEditId(null); load(); } catch (e) { setError(e.message); } finally { setSaving(false); } };
  const remove = async (id) => { if (!window.confirm("Supprimer cet utilisateur ?")) return; try { await userService.remove(id); setMessage("Utilisateur supprimé."); load(); } catch (e) { setError(e.message); } };
  const edit = (u) => { setForm({ nom: u.nom || "", prenom: u.prenom || "", email: u.email || "", mot_de_passe: "", naissance: u.naissance || "", conduite: u.conduite || "", DepartmentId: u.DepartmentId ? String(u.DepartmentId) : "" }); setEditId(u.id); setFieldErrors({}); };
  return <AppLayout title="Utilisateurs"><section className="form-card"><form className="entity-form" onSubmit={submit}><div className="form-grid"><div><label>Nom</label><input value={form.nom} onChange={(e) => setForm({ ...form, nom: e.target.value })} />{fieldErrors.nom && <p className="error-text">{fieldErrors.nom}</p>}</div><div><label>Prénom</label><input value={form.prenom} onChange={(e) => setForm({ ...form, prenom: e.target.value })} />{fieldErrors.prenom && <p className="error-text">{fieldErrors.prenom}</p>}</div><div><label>Email</label><input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} />{fieldErrors.email && <p className="error-text">{fieldErrors.email}</p>}</div><div><label>Mot de passe {editId ? "(laisser vide pour conserver)" : ""}</label><input type="password" value={form.mot_de_passe} onChange={(e) => setForm({ ...form, mot_de_passe: e.target.value })} />{fieldErrors.mot_de_passe && <p className="error-text">{fieldErrors.mot_de_passe}</p>}</div><div><label>Naissance</label><input type="date" value={form.naissance} onChange={(e) => setForm({ ...form, naissance: e.target.value })} /></div><div><label>Conduite</label><select value={form.conduite} onChange={(e) => setForm({ ...form, conduite: e.target.value })}><option value="">-- Choisir --</option><option value="excellente">excellente</option><option value="bonne">bonne</option><option value="passable">passable</option></select></div><div><label>Département</label><select value={form.DepartmentId} onChange={(e) => setForm({ ...form, DepartmentId: e.target.value })}><option value="">-- Aucun --</option>{departments.map((d) => <option key={d.id} value={d.id}>{d.nom}</option>)}</select></div></div>{message && <p className="success-text">{message}</p>}{error && <p className="error-text">{error}</p>}<div className="form-actions"><button className="primary-btn" disabled={saving}>{saving ? "Enregistrement..." : editId ? "Modifier" : "Ajouter"}</button>{editId && <button type="button" className="ghost-btn" onClick={() => { setForm(emptyForm); setEditId(null); setFieldErrors({}); }}>Annuler</button>}</div></form></section>{loading ? <section className="state-box">Chargement...</section> : <section className="card-grid" style={{ marginTop: 20 }}>{items.map((u) => <article className="entity-card" key={u.id}><div className="card-body"><h3>{u.nom} {u.prenom}</h3><p className="entity-badge">{u.email}</p><p className="muted-text">Conduite: {u.conduite || "—"}</p><p className="muted-text">Département: {u.Department?.nom || "—"}</p></div><div className="card-actions"><button className="ghost-btn" onClick={() => edit(u)}>Modifier</button><button className="danger-btn" onClick={() => remove(u.id)}>Supprimer</button></div></article>)}</section>}</AppLayout>;
}

export default Users;
